name: CI on Push and Pull Request

on: [push, pull_request]

jobs:  
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore Xappy.sln
        cd Xappy/Xappy.Android
        msbuild Xappy.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        nuget restore Xappy.sln
        msbuild Xappy/Xappy.iOS/Xappy.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
